version: "3.9"
services:
  db:
    image: authentication
     volumes:
      ---data
    deploy:
      replicas : 2
      rstart policy :
        condition : on-failure
    ports :
        "8000:8000"

  web:
    image: patient
    deploy:
      replicas : 1
      rstart policy :
        condition : on-failure
    ports :
        "8002:8002"

  web:
    image: doctor
    deploy:
      replicas : 1
      rstart policy :
        condition : on-failure
    ports :
        "8001:8001"



